### ISSUE TITLE
You need to have '@sap/cds-dk' installed to use 'cds init'.

### ISSUE THREAD

**Issue by uwe-klinger** [SAP-samples/cloud-cap-walkthroughs#18]
Hi,

when I do as advised here:

https://github.com/SAP-samples/cloud-cap-walkthroughs/blob/master/exercises-node/intro/README.md#2-install-cds

```
npm i -g @sap/cds
```

and then run:

```
cds init bookshop
```

I get the error message:

```
      You need to have '@sap/cds-dk' installed to use 'cds init'.
      Please do so with:

      npm rm -g @sap/cds
      npm i -g @sap/cds-dk
```

If I'm not wrong then you'll need to update the doc.

BR,
Uwe

**Comment by danjoa** [comment]
Thanks Uwe, this is correct → @chgeo @AnneKeller01 @renejeglinsky @iwonahahn and we need to get rid of these redundant docs as discussed

**Comment by chgeo** [comment]
I think, the walkthrough cleanup/merge with the docs is already on the list, right @renejeglinsky ?
Then, let's close this item here (@uwe-klinger I have done the one liner change with a157c16d).
