### ISSUE TITLE
Exercise 3 Get Reviews

### ISSUE THREAD

**Issue by jmryan5** [SAP-samples/cloud-cap-walkthroughs#19]
At the end of Exercise 3, I am receiving the following error when I try and retrieve the Reviews.

GET /catalog/Reviews
Error while executing custom handler: READ on sap.capire.bookstore.CatalogService.Reviews
[2020-03-30T22:07:51.740Z | ERROR | 1216231]: No url configured in credentials for "sap.capire.reviews.ReviewsService"

Any suggestions?

**Comment by dinurp** [comment]
I got it working by configuring url in bookstore/package.json like below

https://github.com/SAP-samples/cloud-cap-samples/blob/CAA265-node-ex3-final/packages/bookstore/package.json
lines 21-30 extracted below
```
    "cds": {
      "requires": {
        "sap.capire.reviews.ReviewsService": {
          "model": "reviews-service",
          "kind": "odata",
          "credentials": {
            "file": "default",
            "url": "http://localhost:4004/reviews"
          }
        }
      }
```
