### ISSUE TITLE
yo generator "Fiori Application"

### ISSUE THREAD

**Issue by whocann** [SAP-samples/cloud-cap-walkthroughs#3]
Hi,

In Exercise 4, step A, the yeoman generator. Any chance we can install the "Fiori Application" generator locally here?

Thanks.

**Comment by chgeo** [comment]
The tools are available in the [VS Code marketplace](https://marketplace.visualstudio.com/search?term=SAP%20Fiori%20Tools&target=VSCode&category=All%20categories&sortBy=Relevance).
