### ISSUE TITLE
Exercise 3 cds run and VSCode

### ISSUE THREAD

**Issue by socenmarc** [SAP-samples/cloud-cap-walkthroughs#4]
Hello,

I'm doing these exercises with VSCode. 
In [exercise 3, part C](https://github.com/SAP-samples/cloud-cap-walkthroughs/blob/master/exercises-node/exercise03/README.md#part-c-consume-events-of-an-external-service) we should run reviews-service and bookstore at the same time and with specific environment variables:

`CDS_REQUIRES_MESSAGING_CREDENTIALS_FILE=default cds run reviews-service --in-memory
`
and
`PORT=4005 cds run bookstore --in-memory`

This does not work for me on the VSCode integrated terminal.
On the other hand, it does work from a new Terminal window (outside VSCode) if I set for example:
`set PORT=4005`
`cds run bookstore --in-memory`

Does anyone know why it doesn't work in VSCode?

Thanks in advance.
Best regards,
Marc

**Comment by chgeo** [comment]
Can you be more specific on the error that you get?

**Comment by socenmarc** [comment]
I get:

> CDS_REQUIRES_MESSAGING_CREDENTIALS_FILE=default : The term 'CDS_REQUIRES_MESSAGING_CREDENTIALS_FILE=default' is not recognized as the name of a cmdlet, 
> function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

![err1](https://user-images.githubusercontent.com/11246514/66939314-23773200-f043-11e9-85b7-a14ab4efd47d.PNG)

Thanks in advance Christian

**Comment by chgeo** [comment]
This is a shell issue.  You seem to use Windows Powershell, which does not understand the Linux/Unix way of defining environment variables.  The way to do this is:
```
$env:CDS_REQUIRES_MESSAGING_CREDENTIALS_FILE = default
cds run
```
and
```
$env:PORT = 4005
cds run bookstore --in-memory
```

**Comment by socenmarc** [comment]
Thanks Christian, it works.

One step further: On a single line (like in the tutorial) would be like that:
`$env:CDS_REQUIRES_MESSAGING_CREDENTIALS_FILE = default ;; cds run`
and 
`$env:PORT = 4005 ;; cds run bookstore --in-memory`

Regards
