### ISSUE TITLE
Exercise 2 - cds init

### ISSUE THREAD

**Issue by ivanmir** [SAP-samples/cloud-cap-walkthroughs#7]
Hi,

The command "cds init reviews-service" creates a dependency with cds version 3.18.1 (which should be the latest version. However, the other projects depend on a lower version 3.17.4. You have to lower the version of the reviews service to make use of the reviews service inside of the bookstore.

Also, the products service schema.cds is missing a field named "name" at the Categories Entity. It should be something like the below:

entity Categories : CodeList {
  key ID   : Integer;
  name     : String;
  parent   : Association to Categories;
  children : Composition of many Categories on children.parent = $self;
}

This field is used at the bookstore CatalogService under Books entity. 

I'm not sure if this field should be of type string or not or 

Best regards,
Ivan

**Comment by David-Kunz** [comment]
Hi Ivan,

Thanks a lot for pointin that out. I fixed the issue by setting the version in ~/.cdsrc.json.
https://github.com/SAP-samples/cloud-cap-samples/commit/95918661126b8092d5bc35285cde420c6f5dafc1

Best regards
David
