### ISSUE TITLE
Command 'cds init' has moved to library @sap/cds-dk

### ISSUE THREAD

**Issue by shlomi-lachmish** [SAP-samples/cloud-cap-walkthroughs#9]
*****************************************************************
The command 'cds init' has moved to library @sap/cds-dk.
Remove the global version of @sap/cds and reinstall @sap/cds-dk.

    npm uninstall -g @sap/cds

    npm install -g @sap/cds-dk

*****************************************************************

**Comment by chgeo** [comment]
Thanks.  We are already aware of this and will update the descriptions.

**Comment by simonefix** [comment]
Any idea why when I click on Reviews I get  this error:
GET /catalog/Reviews
Error while executing custom handler: READ on sap.capire.bookstore.CatalogService.Reviews
[2020-02-03T16:32:14.121Z | ERROR | 1883782]: Cannot rollback: client not found

Thanks!

**Comment by chgeo** [comment]
@simonefix this seems unrelated to the `cds init` topic of this issue. 
If the effect persists on your side, please open a new one.
